In [19]:
import numpy as np

## Intro

In [4]:
a = np.array([[0,0,0],
                [1,1,1]])
print(a)
# 2 axes, the first axis has a length of 2 and the second axis has a length of 3.

[[0 0 0]
 [1 1 1]]


`np.eye(n,m)` defines a 2D identity matrix.

`np.diag` can define either a square 2D array with given values along the diagonal or if given a 2d array returns a 1D array that is only the diagonal elements.


In [21]:
print(np.eye(3))

print(np.eye(3,5))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [22]:
print(np.diag([1,2,3]))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [23]:
print(np.diag([1,2,3], 1))

[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]
 [0 0 0 0]]


In [24]:
a = np.array([[1,2],
              [3,4]])
print(np.diag(a))

[1 4]


### Adding, Removing, and Sorting Elements
`np.sort()` and `np.concatenate()`

In [8]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(np.concatenate((a,b)))

[1 2 3 4 5 6 7 8]


In [10]:
a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6]])
print(np.concatenate((a,b),axis=0))

[[1 2]
 [3 4]
 [5 6]]


In [11]:
a = np.array([1,2,3,4,5,6])
print(a.shape)
a2 = a[np.newaxis, :]
print(a2)
print(a2.shape)

(6,)
[[1 2 3 4 5 6]]
(1, 6)


In [12]:
row_vector = a[np.newaxis, :]
col_vector = a[:, np.newaxis]
print(row_vector.shape)
print(col_vector.shape)
print(col_vector)

(1, 6)
(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [13]:
# you can also expand an array by inserting a new axis at a pecified position 
a3 = np.expand_dims(a, axis = 0)
a4 = np.expand_dims(a, axis=1)
print(a3.shape)
print(a4.shape)

(1, 6)
(6, 1)


### Indexing and Slicing

In [14]:
a = np.arange(12).reshape((3,4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [15]:
print(a[a<5])

[0 1 2 3 4]


In [16]:
five_up = (a>=5)
print(a[five_up])

[ 5  6  7  8  9 10 11]


In [17]:
c = a[(a>2) & (a<11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [18]:
five_up = (a>5) | (a==5)
print(five_up)

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
